#setwd("C:/Users/Hsin-Rui Lin/Documents/Github")
ds <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
ds <- subset(ds, Date=="1/2/2007"| Date=="2/2/2007")

datetime <- strptime(paste(ds$Date, ds$Time, sep=" "), "%d/%m/%Y %H:%M:%S")

png("ExData_Plotting1/plot4.png", height = 720, width = 720)
par(mfrow=c(2,2))
plot(datetime, ds$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(datetime, ds$Voltage, type="l",ylab="Voltage")
plot(datetime, ds$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
points(datetime, ds$Sub_metering_2, type="l", col="red")
points(datetime, ds$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n")
plot(datetime, ds$Global_reactive_power, type="l", ylab="Global_reactive_power")
dev.off()
